---
  - name: Restart apache2
    ansible.builtin.service:
      name: apache2
      state: restarted

  - name: Restart mysql service
    ansible.builtin.service:
      name: mysql
      state: restarted 